title: PaulieOS
description: Now is NOT the time to upgrade your OS  
url: "https://cursor.kevaid.com"
google_analytics: 


# Build settings
theme: minima
plugins:
  - jekyll-feed



sass:
  sass_dir: _sass # All .scss partials go here
  # style: compressed


collections:

  desktop_windows:
    output: true # render each item

  desktop_icons:
    output: true # render each item